apiVersion: v1
kind: PersistentVolume
metadata:
  name: raven-data-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/crypto/raven
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raven-data-pvc
  namespace: crypto
spec:
  volumeName: raven-data-pv
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

---
kind: Service
apiVersion: v1
metadata:
  namespace: crypto
  name: raven
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.4.10
spec:
  selector:
    app: raven
  ports:
  - name: rpc
    port: 8766
  - name: p2p
    port: 8767
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crypto
  name: raven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raven
  template:
    metadata:
      name: raven
      labels:
        app: raven
    spec:
      hostname: raven
      containers:
      - name: ravend
        image: quay.io/declarativesystems/cryptodaemons_raven:4.6.1-7864c39c2
        args:
        - "-server"
        - "-printtoconsole"
        volumeMounts:
        - mountPath: /root/.raven
          name: raven
      restartPolicy: Always
      volumes:
      - name: raven
        persistentVolumeClaim:
          claimName: raven-data-pvc
